site_name: Mai STM32 Docs
site_url: https://example.invalid/Mai_stm32/
theme:
  name: material

nav:
  - Home: index.md

repo_url: https://github.com/example/Mai_stm32
repo_name: Mai_stm32
edit_uri: edit/G431/docs/